# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/end_screen.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_EndScreen(object):
    def setupUi(self, EndScreen):
        EndScreen.setObjectName("EndScreen")
        EndScreen.resize(1100, 750)
        self.verticalLayout = QtWidgets.QVBoxLayout(EndScreen)
        self.verticalLayout.setContentsMargins(100, 100, 100, 100)
        self.verticalLayout.setSpacing(24)
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.resultLabel = QtWidgets.QLabel(EndScreen)
        self.resultLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.resultLabel.setObjectName("resultLabel")
        self.verticalLayout.addWidget(self.resultLabel)
        self.subLabel = QtWidgets.QLabel(EndScreen)
        self.subLabel.setText("")
        self.subLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.subLabel.setObjectName("subLabel")
        self.verticalLayout.addWidget(self.subLabel)
        spacerItem1 = QtWidgets.QSpacerItem(20, 30, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.hboxlayout = QtWidgets.QHBoxLayout()
        self.hboxlayout.setObjectName("hboxlayout")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.hboxlayout.addItem(spacerItem2)
        self.playAgainBtn = QtWidgets.QPushButton(EndScreen)
        self.playAgainBtn.setMinimumSize(QtCore.QSize(240, 55))
        self.playAgainBtn.setObjectName("playAgainBtn")
        self.hboxlayout.addWidget(self.playAgainBtn)
        spacerItem3 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.hboxlayout.addItem(spacerItem3)
        self.quitBtn = QtWidgets.QPushButton(EndScreen)
        self.quitBtn.setMinimumSize(QtCore.QSize(240, 55))
        self.quitBtn.setObjectName("quitBtn")
        self.hboxlayout.addWidget(self.quitBtn)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.hboxlayout.addItem(spacerItem4)
        self.verticalLayout.addLayout(self.hboxlayout)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem5)

        self.retranslateUi(EndScreen)
        QtCore.QMetaObject.connectSlotsByName(EndScreen)

    def retranslateUi(self, EndScreen):
        _translate = QtCore.QCoreApplication.translate
        EndScreen.setWindowTitle(_translate("EndScreen", "Amiral Battı - Oyun Bitti"))
        EndScreen.setStyleSheet(_translate("EndScreen", "background-color: #0d1b2a;"))
        self.resultLabel.setText(_translate("EndScreen", "OYUN BİTTİ"))
        self.resultLabel.setStyleSheet(_translate("EndScreen", "color: #f1c40f; font-size: 42px; font-weight: bold; font-family: Arial;"))
        self.subLabel.setStyleSheet(_translate("EndScreen", "color: #e8f4f8; font-size: 18px; font-family: Arial;"))
        self.playAgainBtn.setText(_translate("EndScreen", "🔄 Tekrar Oyna"))
        self.playAgainBtn.setStyleSheet(_translate("EndScreen", "QPushButton { background-color: #2ecc71; color: white; border-radius: 8px; border: none; font-size: 16px; font-weight: bold; font-family: Arial; } QPushButton:hover { background-color: #27ae60; }"))
        self.quitBtn.setText(_translate("EndScreen", "❌ Çıkış"))
        self.quitBtn.setStyleSheet(_translate("EndScreen", "QPushButton { background-color: #e74c3c; color: white; border-radius: 8px; border: none; font-size: 16px; font-weight: bold; font-family: Arial; } QPushButton:hover { background-color: #c0392b; }"))
