# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/waiting_screen.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_WaitingScreen(object):
    def setupUi(self, WaitingScreen):
        WaitingScreen.setObjectName("WaitingScreen")
        WaitingScreen.resize(1100, 750)
        self.verticalLayout = QtWidgets.QVBoxLayout(WaitingScreen)
        self.verticalLayout.setContentsMargins(50, 50, 50, 50)
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.waitLabel = QtWidgets.QLabel(WaitingScreen)
        self.waitLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.waitLabel.setObjectName("waitLabel")
        self.verticalLayout.addWidget(self.waitLabel)
        self.subWaitLabel = QtWidgets.QLabel(WaitingScreen)
        self.subWaitLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.subWaitLabel.setObjectName("subWaitLabel")
        self.verticalLayout.addWidget(self.subWaitLabel)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)

        self.retranslateUi(WaitingScreen)
        QtCore.QMetaObject.connectSlotsByName(WaitingScreen)

    def retranslateUi(self, WaitingScreen):
        _translate = QtCore.QCoreApplication.translate
        WaitingScreen.setWindowTitle(_translate("WaitingScreen", "Amiral Battı - Bekleniyor"))
        WaitingScreen.setStyleSheet(_translate("WaitingScreen", "background-color: #0d1b2a;"))
        self.waitLabel.setText(_translate("WaitingScreen", "Rakip bekleniyor..."))
        self.waitLabel.setStyleSheet(_translate("WaitingScreen", "color: #e8f4f8; font-size: 24px; font-family: Arial;"))
        self.subWaitLabel.setText(_translate("WaitingScreen", "Lütfen bekleyiniz..."))
        self.subWaitLabel.setStyleSheet(_translate("WaitingScreen", "color: #7fb3d3; font-size: 14px; font-family: Arial;"))
